---
- name: Install essential packages
  apt:
    name: sudo,rsyslog,logrotate,mc,rsync,htop,iotop,tree,vim,python3-pip,acl
    state: present
    update_cache: yes

- name: Configure NTP
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    restart systemd-timesyncd
  when: "'ntpd_servers' not in group_names"

- name: Set Python3 as default
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
