---
- name: Install PG Server
  apt:
    name: postgresql-{{hostvars[groups['pg_servers'][0]]['pg_server_version']}}
    state: present

- name: Install PG Server Dev
  apt:
    name: postgresql-server-dev-{{hostvars[groups['pg_servers'][0]]['pg_server_version']}}
    state: present

- name: Install Python virtualenv
  pip:
    name: virtualenv
  environment:
    HTTP_PROXY: '{{ pip_proxy }}'
    HTTPS_PROXY: '{{ pip_proxy }}'

- name: Install Python psycopg2
  pip:
    name: psycopg2
    virtualenv: '{{ venv }}'
  environment:
    HTTP_PROXY: '{{ pip_proxy }}'
    HTTPS_PROXY: '{{ pip_proxy }}'

- name: PG add my user
  postgresql_user:
    name: '{{ username }}'
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB
  vars:
    ansible_python_interpreter: '{{venv}}/bin/python'
  become: yes
  become_user: postgres
